### ISSUE TITLE
https://centralia.instructure.com

### ISSUE THREAD

**Issue by russ5686** [da-stoi/canvas-strikethrough#10]
**Enter the full base URL like the example**: https://canvas.wpi.edu/

*Note: If your university/school has a URL that ends in `.instructure.com` please **do not** submit a URL add request. The extension should already work on your Canvas page.*

**Comment by da-stoi** [comment]
The Canvas link you have submitted is already whitelisted since it ends with `.instructure.com`. 
Please make sure to read all instructions before submitting URL add requests.

**Comment by russ5686** [comment]
Why, when you refresh the page, does the strike through go away as if never marked off? This would be amazing, but it doesn’t work.

Russ McCarthy


On Apr 25, 2024, at 10:24 AM, Daniel ***@***.***> wrote:

﻿

Closed #10<https://github.com/da-stoi/canvas-strikethrough/issues/10> as not planned.
