### ISSUE TITLE
URL Add Request

### ISSUE THREAD

**Issue by holland2unlv** [da-stoi/canvas-strikethrough#4]
**Enter the full base URL like the example**: https://canvas.wpi.edu/

*Note: If your university/school has a URL that ends in `.instructure.com` please **do not** submit a URL add request. The extension should already work on your Canvas page.*

Hi, please help.
Can you please give me more information on how to use this extension? I am using UNLV.instructure.com and I can see on the bottom right of the month calendar screen where it says "Canvas Strikethrough Checked" so I believe I correctly installed the extension but I do not see anywhere the option to strikethrough and mark an event as complete.

Thanks,
Jeff
holland2@unlv.nevada.edu

**Comment by da-stoi** [comment]
> Can you please give me more information on how to use this extension?
Sure thing Jeff. There are two main places where you can mark off assignments as complete. 

The first place is on your canvas calendar, in your case, the link to this would be https://unlv.instructure.com/calendar#view_name=month. When you click on an assignment, quiz, or page on that calendar a popup should appear like normal. Inside that popup should be a new button called "Mark as complete" clicking this once should change the button to say "Mark as incomplete" and the item that you clicked on should now appear with a strikethrough effect.

The second place is on the assignment, page, or quiz page itself. There you should see the same button, clicking it and returning to the calendar view will show that assignment as complete.

Note that marking an assignment as complete is purely visual. This does not turn anything in, nor does it notify your instructor. It is only intended for students with instructors who add assignments without online submissions, or dated pages that always show as incomplete.

Hope this was helpful, 
Daniel

**Comment by holland2unlv** [comment]
Will this also work for assignments I created and added myself on the
calendar such as when I add reading assignments?

**Comment by da-stoi** [comment]
Canvas Strikethrough does not currently support custom events if this is what you mean. This might be a feature down the road, however, it was deprioritized due to user feedback.

**Comment by lyonschris2004** [comment]
https://learn.vccs.edu/  Please, thanks!
